// Generated by scripts/import-content.mjs. Do not edit by hand.
import type { ImageSource } from '@briansunter/nib-images'

import wi0 from '../assets/site-assets/68d32d0a-a41f-4370-bf64-60dacba7e3ea.jpeg?nib-image'
import wi1 from '../assets/site-assets/convocards-launch-retro/image.jpg?nib-image'
import wi2 from '../assets/site-assets/1713157492098_0.png?nib-image'
import wi3 from '../assets/site-assets/hawaii-cover_1710985966457_0.jpg?nib-image'
import wi4 from '../assets/site-assets/Screenshot_2023-09-27_at_1.28.29_PM_1695857318835_0.png?nib-image'
import wi5 from '../assets/site-assets/coffee_quality_by_country_boxplot.png?nib-image'
import wi6 from '../assets/site-assets/Screenshot_2023-03-14_at_3.01.45_PM_1678842139677_0.png?nib-image'
import wi7 from '../assets/site-assets/honolulu_1676694313546_0.jpg?nib-image'
import wi8 from '../assets/site-assets/Screenshot_2023-02-02_at_1.42.14_PM_1675381393942_0.png?nib-image'
import wi9 from '../assets/site-assets/summarize_1674095683669_0.gif?nib-image'
import wi10 from '../assets/site-assets/binary-search-cover.png?nib-image'
import wi11 from '../assets/site-assets/heap_1673042424667_0.jpg?nib-image'
import wi12 from '../assets/site-assets/recurrence-masters-theorem-cover.png?nib-image'
import wi13 from '../assets/site-assets/recurrence-subtracting-cover.png?nib-image'
import wi14 from '../assets/site-assets/books-read-site_1672793412235_0.jpg?nib-image'
import wi15 from '../assets/site-assets/basb_1672455079106_0.jpeg?nib-image'
import wi16 from '../assets/site-assets/1071614177.01._SCLZZZZZZZ_SX500_1670647404075_0.jpg?nib-image'
import wi17 from '../assets/site-assets/stop_1672218528540_0.jpg?nib-image'
import wi18 from '../assets/site-assets/Screen_Shot_2022-09-11_at_8.35.17_PM_1668815306606_0.png?nib-image'
import wi19 from '../assets/site-assets/logseq-openai-hero.png?nib-image'
import wi20 from '../assets/site-assets/image_1667858995655_0_1667859078784_0.jpeg?nib-image'
import wi21 from '../assets/site-assets/image_1662086881256_0.png?nib-image'
import wi22 from '../assets/site-assets/ss_21b43d4cb49ef3332eefbb4957ec96e075543ef1.1920x1080_1666656957286_0.jpg?nib-image'
import wi23 from '../assets/site-assets/Screenshot_2022-12-07_at_12.29.34_PM_1670452221345_0.png?nib-image'
import wi24 from '../assets/site-assets/image_1662087569135_0.png?nib-image'
import wi25 from '../assets/site-assets/image_1662087082755_0.png?nib-image'
import wi26 from '../assets/site-assets/herzog_1672134562808_0.jpeg?nib-image'
import wi27 from '../assets/site-assets/image_1665465573710_0.png?nib-image'
import wi28 from '../assets/site-assets/beebob_checkmark_in_checkbox_app_eea7631b-472d-4e91-acba-590250d7106c_1672269960068_0.jpg?nib-image'
import wi29 from '../assets/site-assets/image_1662087221258_0.png?nib-image'
import wi30 from '../assets/site-assets/image_1660798082719_0.png?nib-image'
import wi31 from '../assets/site-assets/FYqjtUnX0AAsVJEE_1672133776857_0.jpeg?nib-image'
import wi32 from '../assets/site-assets/image_1657735112414_0_1672132400967_0.png?nib-image'
import wi33 from '../assets/site-assets/image_1657488579000_0_1672131758605_0.png?nib-image'
import wi34 from '../assets/site-assets/41ZZY5kzLL_1670306664477_0.jpg?nib-image'
import wi35 from '../assets/site-assets/image_1657488579000_0_1672131763262_0.png?nib-image'
import wi36 from '../assets/site-assets/chinese-robot_1672272679577_0.jpg?nib-image'
import wi37 from '../assets/site-assets/image_1662087305440_0.png?nib-image'
import wi38 from '../assets/site-assets/kubernetes_1672272543261_0.png?nib-image'
import wi39 from '../assets/site-assets/get-youtube-captions_1672134947975_0.jpg?nib-image'
import wi40 from '../assets/site-assets/kubernetes-gpt_1672123546658_0.jpeg?nib-image'
import wi41 from '../assets/site-assets/daily-highlight_1672273385215_0.jpg?nib-image'
import wi42 from '../assets/site-assets/image_1660689722955_0.png?nib-image'
import wi43 from '../assets/site-assets/image_1661149276371_0.png?nib-image'
import wi44 from '../assets/site-assets/travels-with-charley_1672052430785_0.jpeg?nib-image'
import wi45 from '../assets/site-assets/image_1661147875071_0.png?nib-image'
import wi46 from '../assets/site-assets/image_1661064164296_0.png?nib-image'
import wi47 from '../assets/site-assets/image_1661224819843_0.png?nib-image'
import wi48 from '../assets/site-assets/image_1661148998101_0.png?nib-image'
import wi49 from '../assets/site-assets/clojure_logo.svg_1660983015847_0.png?nib-image'

export const writingImageMap: Record<string, ImageSource> = {
  "central-pacific-update": wi0,
  "convocards-launch-retro": wi1,
  "newsletter/issue-16": wi2,
  "newsletter/issue-15": wi3,
  "newsletter/issue-14": wi4,
  "newsletter/issue-13": wi5,
  "newsletter/issue-12": wi6,
  "newsletter/issue-11": wi7,
  "newsletter/issue-10": wi8,
  "logseq-openai/popup": wi9,
  "binary-search": wi10,
  "heap": wi11,
  "recurrence-relation-masters-theorem-dividing": wi12,
  "recurrence-relation-masters-theorem-subtracting": wi13,
  "books-read-in-2022": wi14,
  "building-a-second-brain": wi15,
  "ai-learning-resources": wi16,
  "newsletter/issue-9": wi17,
  "why-large-language-models-are-interesting": wi18,
  "logseq-openai-prompt-template": wi19,
  "headphone-eye-mask": wi20,
  "omnivore-logseq-guide": wi21,
  "soma": wi22,
  "algorithms": wi23,
  "intro-to-algorithms": wi24,
  "logseq-getting-started": wi25,
  "werner-herzog-rules-for-filmmaking": wi26,
  "newsletter/issue-8": wi27,
  "logseq-projects": wi28,
  "notetaking-with-ai": wi29,
  "you-and-your-research": wi30,
  "newsletter/issue-7": wi31,
  "newsletter/issue-6": wi32,
  "algorithms-boot-camp": wi33,
  "almanack-of-naval-ravikant": wi34,
  "newsletter/issue-5": wi35,
  "gpt3-chinese-language-tutor": wi36,
  "newsletter/issue-4": wi37,
  "how-to-use-gpt3-to-learn-kubernetes": wi38,
  "newsletter/issue-3": wi39,
  "newsletter/issue-2": wi40,
  "daily-highlight-productivity-technique": wi41,
  "newsletter/issue-1": wi42,
  "ai-powered-notetaking-with-the-gpt-3-logseq-plugin": wi43,
  "travels-with-charley": wi44,
  "python-setup-pyenv-poetry": wi45,
  "five-minute-journal": wi46,
  "how-to-take-smart-notes": wi47,
  "emacs-daemon-mode-on-macos": wi48,
  "why-clojure": wi49,
}
