import {
  definePlugin,
  type HeadElement,
  type NibRenderedPage,
  type NibRenderPageContext,
} from '@briansunter/nib/plugin'
import { sourceHead } from '../data/source-head'

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;')
}

/**
 * Replays the canonical site's route-specific document metadata exactly.
 *
 * The source manifest is generated by import-content from the canonical
 * production build. Body-level schema emitted by React renderers is removed
 * because the original schema scripts are restored in the document head.
 */
export function sourceMetadata() {
  return definePlugin({
    name: 'personal-site-source-metadata',
    renderer() {
      return {
        head(context: NibRenderPageContext) {
          const record = sourceHead[context.route.path]
          if (!record) throw new Error(`Missing source metadata for ${context.route.path}`)
          const elements: HeadElement[] = [
            { tag: 'link', attributes: { rel: 'canonical', href: record.canonical } },
          ]
          if (record.markdownAlternate) {
            elements.push({
              tag: 'link',
              attributes: {
                rel: 'alternate',
                type: 'text/markdown',
                href: record.markdownAlternate,
              },
            })
          }
          for (const meta of record.metas) {
            elements.push({
              tag: 'meta',
              attributes: {
                [meta.attribute]: meta.key,
                content: meta.content,
              },
            })
          }
          for (const content of record.structuredData) {
            elements.push({
              tag: 'script',
              attributes: { type: 'application/ld+json' },
              content,
            })
          }
          return { elements }
        },
        transformPage(
          page: NibRenderedPage,
          context: NibRenderPageContext,
        ) {
          const record = sourceHead[context.route.path]
          if (!record) throw new Error(`Missing source metadata for ${context.route.path}`)
          const head = page.head
            .replace(/<title>[\s\S]*?<\/title>/i, `<title>${escapeHtml(record.title)}</title>`)
            .replace(
              /<meta name="description" content="[^"]*" \/>/i,
              `<meta name="description" content="${escapeHtml(record.description)}" />`,
            )
          const html = page.html.replace(
            /<script\b[^>]*type=(?:"application\/ld\+json"|'application\/ld\+json')[^>]*>[\s\S]*?<\/script>/gi,
            '',
          )
          return { ...page, head, html }
        },
      }
    },
  })
}
