export { definePlugin } from './framework/plugin'
export type { HeadAttributeValue, HeadContribution, HeadElement, HeadTagName } from './framework/types'
export type {
  Awaitable,
  NibCommand,
  NibFinalizeContext,
  NibMode,
  NibPageRouteRegistration,
  NibPlugin,
  NibPluginRoute,
  NibPluginSetupContext,
  NibPluginSetupPhase,
  NibPluginSetupResult,
  NibPluginSiteConfig,
  NibRedirectRouteRegistration,
  NibRenderedPage,
  NibResolvedPageRoute,
  NibResolvedRedirectRoute,
  NibResolvedResourceRoute,
  NibResolvedRoute,
  NibResourceRouteRegistration,
  NibRendererExtension,
  NibRendererPluginContext,
  NibRenderPageContext,
  NibRouteRegistration,
  NibRoutesPluginContext,
  NibRoutesResolvedPluginContext,
  NibVitePluginContext,
  NibViteTarget,
} from './framework/plugin'
